import { readFile, writeFile, mkdir, cp, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, join } from 'node:path';
import { parseEnv } from 'node:util';
import { execFileSync } from 'node:child_process';

export function validateHub(value) {
  const url = new URL(value);
  const local = ['localhost', '127.0.0.1', '[::1]'].includes(url.hostname);
  if ((url.protocol !== 'https:' && !(local && url.protocol === 'http:')) ||
      url.username || url.password || url.search || url.hash || url.pathname !== '/') {
    throw new Error('BRO_RELAY_HUB_URL must be an HTTPS origin (HTTP allowed for localhost tests).');
  }
  return url.origin;
}

export async function buildSkill(root = fileURLToPath(new URL('../', import.meta.url))) {
  const runtime = join(root, 'skills/bro-connect/scripts/runtime');
  for (const file of ['cli/index.js', 'cli/sdk.js', 'config.js', 'extension/protocol.js']) {
    await mkdir(resolve(runtime, file, '..'), { recursive: true });
    await cp(join(root, file), join(runtime, file));
  }
  const { version } = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
  await writeFile(join(runtime, 'package.json'), JSON.stringify({ type: 'module', version }, null, 2) + '\n');
}

export async function build(root = fileURLToPath(new URL('../', import.meta.url))) {
  const { version } = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
  let env = {};
  try { env = parseEnv(await readFile(join(root, '.env'), 'utf8')); }
  catch (error) { if (error.code !== 'ENOENT') throw error; }
  const defaults = parseEnv(await readFile(join(root, '.env.example'), 'utf8'));
  const hub = validateHub(process.env.BRO_RELAY_HUB_URL || env.BRO_RELAY_HUB_URL || defaults.BRO_RELAY_HUB_URL);
  const config = `// Generated by npm run build. Public endpoint only.\nexport const HUB_URL = ${JSON.stringify(hub)};\n`;
  await writeFile(join(root, 'config.js'), config);
  await writeFile(join(root, 'extension/config.js'), config);
  const manifest = JSON.parse(await readFile(join(root, 'extension/manifest.json'), 'utf8'));
  manifest.version = version;
  manifest.host_permissions = [`${hub}/*`];
  await writeFile(join(root, 'extension/manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  await buildSkill(root);
  const dist = join(root, 'dist');
  await mkdir(dist, { recursive: true });
  const staged = join(dist, 'bro-relay-debug-extension');
  await rm(staged, { recursive: true, force: true });
  await rm(join(dist, 'extension'), { recursive: true, force: true });
  await cp(join(root, 'extension'), staged, { recursive: true });
  await cp(join(root, 'LICENSE'), join(staged, 'LICENSE'));
  await cp(join(root, 'THIRD_PARTY_NOTICES.md'), join(staged, 'THIRD_PARTY_NOTICES.md'));
  // Version only in the zip name; the inner folder stays fixed so users can overwrite-install.
  const archive = join(dist, `bro-relay-debug-extension-${version}.zip`);
  await rm(archive, { force: true });
  execFileSync('zip', ['-qr', archive, 'bro-relay-debug-extension'], { cwd: dist });
  return { version, hub, extension: staged, archive };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { console.log(JSON.stringify(await build(), null, 2)); }
  catch (error) { console.error(error.message); process.exitCode = 1; }
}
